### ISSUE TITLE
Schema verification doesn't work in a nix container

### ISSUE THREAD

**Issue by allgreed** [dynatrace-oss/dt-cli#150]
```
dt ext validate-schema --instance src/extension.yaml --schema-entrypoint /nix/store/lv61sl5zif2r1886850lia2qzm2d9jic-extension-dev-env/bin/../schemas/extension.schema.json
Traceback (most recent call last):
  File "dtcli/__main__.py", line 9, in <module>
  File "dtcli/__main__.py", line 5, in main
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "dtcli/scripts/dt.py", line 814, in validate_schema
  File "dtcli/validate_schema.py", line 52, in validate_schema
  File "json/__init__.py", line 293, in load
  File "encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 790: ordinal not in range(128)
[96019] Failed to execute script '__main__' due to unhandled exception!
make: *** [/nix/store/lv61sl5zif2r1886850lia2qzm2d9jic-extension-dev-env/bin/__dt_ext_common_make:39: lint] Error 1
```

**To Reproduce**
```
docker run -it -v $(pwd):/ext nixos/nix:2.9.1 bash
git clone https://github.com/dynatrace-extensions/palo-alto.generic.git
cd palo-alto.generic
git checkout 7af7eeeb1407858815b91ffb03ab1aee57c8bb91
nix-shell
# now wait
make lint
```

Faster way to get the same behaviour, but not 100% sure they're equivalent:
```
# in Palo Alto generic repo, same commit
LANG= make lint
```

**Expected behavior**
0 exit code

**Desktop (please complete the following information):**
 -  Linux

**Comment by vduseev** [comment]
Out of scope
