### ISSUE TITLE
dt ext genca broken on 1.6.11

### ISSUE THREAD

**Issue by dlopes7** [dynatrace-oss/dt-cli#156]
### Steps to reproduce

```shell
pip install -U dt-cli==1.6.11
dt ext genca
```

Generates:

```
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\tmp\venv\Scripts\dt.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'dtcli.cli'
```

The same command works fine on `1.6.10`

**Comment by vduseev** [comment]
Fixed in 1.6.12
