### ISSUE TITLE
Unsupported/Missing 'Content-Type' header.

### ISSUE THREAD

**Issue by cpz2019** [dynatrace-oss/dt-cli#170]
**Describe the bug**

```shell
$ dt extension validate custom.data.quality.consistency.lima.usage.zip --tenant-url https://deve2e.dev.dynatracelabs.com --api-token ****

 [2024-04-25T08:11:37.869Z] Extension validation failed!
 [2024-04-25T08:11:37.869Z] Traceback (most recent call last):
 [2024-04-25T08:11:37.870Z]   File "/usr/lib/python3.11/site-packages/dtcli/server_api.py", line 29, in validate
 [2024-04-25T08:11:37.870Z]     response.raise_for_status()
 [2024-04-25T08:11:37.871Z]   File "/usr/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
 [2024-04-25T08:11:37.872Z]     raise HTTPError(http_error_msg, response=self)
 [2024-04-25T08:11:37.874Z] requests.exceptions.HTTPError: 415 Client Error: Unsupported Media Type for url: https://deve2e.dev.dynatracelabs.com/api/v2/extensions?validateOnly=true
 [2024-04-25T08:11:37.874Z] 
 [2024-04-25T08:11:37.874Z] During handling of the above exception, another exception occurred:
 [2024-04-25T08:11:37.874Z] 
 [2024-04-25T08:11:37.875Z] Traceback (most recent call last):
 [2024-04-25T08:11:37.875Z]   File "/usr/bin/dt", line 8, in <module>
 [2024-04-25T08:11:37.875Z]     sys.exit(main())
 [2024-04-25T08:11:37.875Z]              ^^^^^^
 [2024-04-25T08:11:37.876Z]   File "/usr/lib/python3.11/site-packages/dtcli/__main__.py", line 5, in main
 [2024-04-25T08:11:38.209Z]     dtcli.scripts.dt.main()
 [2024-04-25T08:11:38.210Z]   File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
 [2024-04-25T08:11:38.211Z]     return self.main(*args, **kwargs)
 [2024-04-25T08:11:38.211Z]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
 [2024-04-25T08:11:38.212Z]   File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
 [2024-04-25T08:11:38.212Z]     rv = self.invoke(ctx)
 [2024-04-25T08:11:38.213Z]          ^^^^^^^^^^^^^^^^
 [2024-04-25T08:11:38.214Z]   File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
 [2024-04-25T08:11:38.214Z]     return _process_result(sub_ctx.command.invoke(sub_ctx))
 [2024-04-25T08:11:38.215Z]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 [2024-04-25T08:11:38.216Z]   File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
 [2024-04-25T08:11:38.217Z]     return _process_result(sub_ctx.command.invoke(sub_ctx))
 [2024-04-25T08:11:38.217Z]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 [2024-04-25T08:11:38.218Z]   File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
 [2024-04-25T08:11:38.219Z]     return ctx.invoke(self.callback, **ctx.params)
 [2024-04-25T08:11:38.219Z]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 [2024-04-25T08:11:38.220Z]   File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
 [2024-04-25T08:11:38.221Z]     return __callback(*args, **kwargs)
 [2024-04-25T08:11:38.221Z]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 [2024-04-25T08:11:38.222Z]   File "/usr/lib/python3.11/site-packages/dtcli/scripts/dt.py", line 159, in wrapper
 [2024-04-25T08:11:38.222Z]     return func(*args, **kwargs)
 [2024-04-25T08:11:38.223Z]            ^^^^^^^^^^^^^^^^^^^^^
 [2024-04-25T08:11:38.224Z]   File "/usr/lib/python3.11/site-packages/dtcli/scripts/dt.py", line 721, in validate
 [2024-04-25T08:11:38.225Z]     server_api.validate(extension_zip, kwargs["tenant_url"], kwargs["api_token"])
 [2024-04-25T08:11:38.226Z]   File "/usr/lib/python3.11/site-packages/dtcli/server_api.py", line 33, in validate
 [2024-04-25T08:11:38.226Z]     raise dtcliutils.ExtensionValidationError(response.text)
 [2024-04-25T08:11:38.228Z] dtcli.utils.ExtensionValidationError: {"error":{"code":415,"message":"Unsupported/Missing 'Content-Type' header."}}
```

**To Reproduce**
1. Run `dt extension validate`

**Additional context**
`usr/lib/python3.11/site-packages/dtcli/server_api.py`

**Comment by vduseev** [comment]
Hi @cpz2019, just tried to reproduce and it works.

It seems you are using an outdated version. Even line numbers do not match with the latest. For comparison:
* The error in your logs is thrown from line number `33` in `server_api.py`.
* Currently this error, when it occurs, is thrown from line number `36` in the same file: https://github.com/dynatrace-oss/dt-cli/blob/9cf9309336f25e06920d7f9b7ee60a468731f539/dtcli/server_api.py#L36
